name = "BitVectorExtensions"
uuid = "907b72a9-c2f8-476c-8cd9-810b79987fb4"
authors = ["Andrew J. Radcliffe <andrewjradcliffe@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
